---
apiVersion: v1
kind: Pod

metadata:
  name: apache
  labels:
    app: website

spec:
  containers:
    - name: apache
      image: #{website-image-latest}#
      ports:
        - containerPort: 80